### ISSUE TITLE
broken link - courses/osint

### ISSUE THREAD

**Issue by beeburrt** [f141ne0/Cybersecurity-Journey#1]
Mega says:

> This link is unavailable as the user's account has been closed for gross violation of MEGA's Terms of Service

And the "Terms of Service" part is a link to, I'm assuming, the terms of service.

Anyways, can't access the OSINT course, and also I want to say thank you for providing these resources

**Comment by neospl0it** [comment]
**Access to Other OSINT Courses**

Hello @beeburrt,

Thank you for bringing up the issue with the broken link. While that specific course is currently unavailable, you can access other OSINT-related courses and resources here:

- **Telegram OSINT Course**: [https://t.me/project_entity/576](https://t.me/project_entity/576)
- **OSINT Course by @Hacktiva**: [https://mega.nz/folder/1GFRjJhA#aYrS5y3rie7zlgsxhi3reQ](https://mega.nz/folder/1GFRjJhA#aYrS5y3rie7zlgsxhi3reQ)
- **Twitter OSINT, Hacking, Ethical Hackers, and OSINTeers**: [https://t.me/project_entity/346](https://t.me/project_entity/346)

I hope these resources help you continue your OSINT learning journey! Thanks again for your support.

**Comment by beeburrt** [comment]
<details>
<summary>question:</summary>
Thanks!

Hey, I've never had a Telegram account before,

How would one go about creating a Telegram acct that is NOT linked to their true identity?
</details>
